---
ID: "10d29ffc-3043-5710-8f88-4ed02e71bbc9"
Parent: "a7b80ca9-a185-59cb-bb2c-bf13557b7f97"
Template: "a7b80ca9-a185-59cb-bb2c-bf13557b7f97"
Path: "/sitecore/templates/Project/Styleguide/Styleguide-RouteFields/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190620T024503Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
